# Generated by Django 4.2 on 2023-07-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionno', models.IntegerField(default=0, unique=True)),
                ('question', models.TextField(max_length=1024)),
                ('answer', models.TextField(max_length=1024)),
                ('hyperlinktext', models.TextField(blank=True, max_length=1024, null=True)),
                ('hyperlink', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
