# Generated by Django 4.2 on 2023-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_faq_questionno'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1024)),
                ('description', models.TextField(max_length=2048)),
                ('venue', models.TextField(max_length=1024)),
                ('mode', models.TextField(max_length=1024)),
                ('dateandtime', models.DateTimeField()),
                ('imageurl', models.ImageField(upload_to='events/')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
