# Generated by Django 4.2 on 2023-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
