# Generated by Django 4.2 on 2023-07-31 10:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_events_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='imageurl',
            field=models.ImageField(upload_to=home.models.generate_filename),
        ),
    ]
