# Generated by Django 4.2 on 2023-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_events_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('registration_no', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('study_year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('6', 'sixth Year')], max_length=1)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users_profile/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('tryhackme_link', models.URLField(blank=True)),
                ('hackthebox_link', models.URLField(blank=True)),
            ],
        ),
    ]
