# Generated by Django 4.2 on 2023-08-05 00:58

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='discord_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.generate_profile_image_filename),
        ),
    ]
