# Generated by Django 4.2 on 2023-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_userdetails_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='link',
            new_name='whatsapp_group_link',
        ),
        migrations.RemoveField(
            model_name='events',
            name='dateandtime',
        ),
        migrations.AddField(
            model_name='events',
            name='end_dateandtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_dateandtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
