# Generated by Django 4.2 on 2023-08-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_eventregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='registration_no',
            field=models.CharField(max_length=50),
        ),
    ]
